///////////////////////////////////////////////////////////////////////////////
// kuka_interfaceInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "kuka_interfaceServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
