///////////////////////////////////////////////////////////////////////////////
// motive_interfaceClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "motive_interfaceClassFactory.h"
#include "motive_interfaceServices.h"
#include "motive_interfaceVersion.h"
#include "motive_interface_module.h"

BEGIN_CLASS_MAP(Cmotive_interfaceClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_motive_interfaceCmotive_interface_module, SRVNAME_MOTIVE_INTERFACE "!Cmotive_interface_module", Cmotive_interface_module)
///</AutoGeneratedContent>
END_CLASS_MAP()

Cmotive_interfaceClassFactory::Cmotive_interfaceClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MOTIVE_INTERFACE)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(motive_interface));
#endif //defined(TCDBG_UNIT_VERSION)
}

