// ****************** CcontrollerClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "Ccontroller.h"
#include "CcontrollerClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(CcontrollerClassFactory)
	CLASS_ENTRY_RT(CID_controller,SRVNAME_controller "!Ccontroller", Ccontroller)
END_CLASS_MAP()


CcontrollerClassFactory::CcontrollerClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_controller)); 
}

