// ****************** CcontrollerDrv.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CCONTROLLERDRV_H_INCLUDED
#define CCONTROLLERDRV_H_INCLUDED

#include "TcPch.h"

#define controllerDRV_NAME			"controller"
#define controllerDRV_Major			1
#define controllerDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CcontrollerDrv

#include "ObjDriver.h"

class CcontrollerDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
  //////////////////////////////////////////////////////
  // VxD-Services exported by this driver
  static unsigned long _cdecl controller_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( controllerDRV)
	VxD_Service( controller_GetVersion		)
End_VxD_Service_Table


#endif
