// ****************** CcontrollerClassFactory.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#ifndef CCONTROLLERCLASSFACTORY_H_INCLUDED
#define CCONTROLLERCLASSFACTORY_H_INCLUDED

#include "ObjClassFactory.h"

class CcontrollerClassFactory : public CObjClassFactory
{
public:
	CcontrollerClassFactory();
	
	// ITComClassFactory
	DECLARE_CLASS_MAP()
};

#endif
