// ****************** CcontrollerDrv.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "CcontrollerDrv.h"
#include "Ccontroller.h"
#include "CcontrollerClassFactory.h"
#include "controllerVersion.h"

DECLARE_GENERIC_DEVICE(controllerDRV)
#undef DEVICE_MAIN

IOSTATUS CcontrollerDrv::OnLoad( )
{
	TRACE(_T("CcontrollerClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CcontrollerClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CcontrollerDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CcontrollerDrv::controller_GetVersion( )
{
	return(0);
}