// ****************** Ccontroller.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#pragma once

#include "rtwtypes.h"
#include "TcPch.h"
#include "TcMatSim.h"
#include "TcIoInterfaces.h"
#include "TcInterfaces.h"
#include "TcRtInterfaces.h"
#include "controllerInterfaces.h"
#include "controller.h"

typedef TctModuleContextExecutionInfo controllerExecutionInfoArrType[1];








typedef struct{
	CLSID ClassId;
	unsigned int BuildTimeStamp;
	unsigned int ModelCheckSum[4];
	unsigned int ModelVersion[4];
	unsigned int TwinCatVersion[4];
	unsigned int TcTargetVersion[4];
	unsigned int MatlabVersion[4];
	unsigned int SimulinkVersion[4];
	unsigned int CoderVersion[4];
	GUID TcTargetLicenseId;
} TctModuleInfoType;

typedef struct{
	bool Debug;
} TctModuleBuildInfoType;


///////////////////////////////////////////////////////////////////////////////
// Module class
///////////////////////////////////////////////////////////////////////////////
class Ccontroller:
  public ITcCyclic,
  public ITcPostCyclic,
  public ITcADI,
  public ITcWatchSource,
  public CTcMatSimModuleBase
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_controller)
	DECLARE_ITCOMOBJECT_SETSTATE()
	DECLARE_PARA();
	DECLARE_ITCOMOBJECT_LOCKOP_IMPL()

	Ccontroller();
	~Ccontroller();

	static int GetInstanceCnt();
	
	// ITcCyclic
	HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcPostCyclic
	HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcADI
	DECLARE_ITCADI();

	// ITcWatchSource
	DECLARE_ITCWATCHSOURCE();
	
	// parameters and signals
	bool m_CycleUpdateExecuted;
	TctModuleContextExecutionInfo m_ModuleExecutionInfo[1];
	TctModuleInfoType m_ModuleInfo;
	TctModuleBuildInfoType m_ModuleBuildInfo;
	RT_MODEL_controller_T m_SimStruct;
	ExtU_controller_T m_Input;
	ExtY_controller_T m_Output;
	B_controller_T m_BlockIO;
	P_controller_T m_ModelParameters;
	DW_controller_T m_DWork;
	RTWExtModeInfo m_controller_44_rt_ExtModeInfo;
	DataTypeTransInfo m_controller_111_dtInfo;

	
private:
	// interface pointer to the external mode server
	ITcMatSimExtModeServer* m_ipExtModeServer;

	// private methods
    DECLARE_OBJPARAWATCH_MAP();
    DECLARE_OBJDATAAREA_MAP();
	HRESULT InitMembers();
	HRESULT CheckAndAdaptCycleTimes();
	
	void controller_iiwa_jacobian (const real_T q[7], real_T param_l__2, real_T param_l__3, real_T param_l__4, real_T param_l__5, real_T param_l__6, real_T param_l__7, real_T tmpreturn[42]);
	void controller_iiwa_jacobian_p (const real_T q[7], const real_T q__p[7], real_T param_l__2, real_T param_l__3, real_T param_l__4, real_T param_l__5, real_T param_l__6, real_T param_l__7, real_T tmpreturn[42]);
	void controller_iiwa_reduced_inertia_matrix (const real_T q[7], const s3SKlq7RIjogRS1TCXHHwEH_controller_T *param, real_T tmpreturn[49]);
	void controller_iiwa_reduced_coriolis_matrix (const real_T q[7], const real_T q__p[7], const s3SKlq7RIjogRS1TCXHHwEH_controller_T *param, real_T tmpreturn[49]);
	void controller_power (const real_T a_data[], const int32_T *a_size, real_T y_data[], int32_T *y_size);
	void controller_mldivide (const real_T A[49], real_T B[7]);
	void controller_output (void);
	void controller_update (void);
	void controller_initialize (void);
	void controller_terminate (void);
	void MdlOutputs (int_T tid);
	void MdlUpdate (int_T tid);
	void MdlInitializeSizes (void);
	void MdlInitializeSampleTimes (void);
	void MdlInitialize (void);
	void MdlStart (void);
	void MdlTerminate (void);
	RT_MODEL_controller_T* controller (void);
	real_T rtGetInf (void);
	real32_T rtGetInfF (void);
	real_T rtGetMinusInf (void);
	real32_T rtGetMinusInfF (void);
	real_T rtGetNaN (void);
	real32_T rtGetNaNF (void);
	void rt_InitInfAndNaN (size_t realSize);
	boolean_T rtIsInf (real_T value);
	boolean_T rtIsInfF (real32_T value);
	boolean_T rtIsNaN (real_T value);
	boolean_T rtIsNaNF (real32_T value);


	// static members
	static int _InstanceCnt;

};
