// ****************** controller_dt.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * controller_dt.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "pDummyInstancecontroller".
 *
 * Model version              : 1.2877
 * Simulink Coder version : 8.13 (R2017b) 24-Jul-2017
 * C++ source code generated on : Mon Jun 22 12:41:17 2020
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Execution efficiency
 * Validation result: Not run
 */

#include "ext_types.h"

/* data type size table */
static uint_T rtDataTypeSizes[] = {
  sizeof(real_T),
  sizeof(real32_T),
  sizeof(int8_T),
  sizeof(uint8_T),
  sizeof(int16_T),
  sizeof(uint16_T),
  sizeof(int32_T),
  sizeof(uint32_T),
  sizeof(boolean_T),
  sizeof(fcn_call_T),
  sizeof(int_T),
  sizeof(pointer_T),
  sizeof(action_T),
  2*sizeof(uint32_T),
  sizeof(struct_DSpp81f2dpk9LO8OYuDS2D),
  sizeof(struct_mXDYE1zZu7EzH2iXvb11SH),
  sizeof(struct_rcDhSIcYe0anGh37xlb6SC),
  sizeof(struct_6KsaStIdjpBuRBst70TZDB),
  sizeof(robot_model)
};

/* data type name table */
static const char_T * rtDataTypeNames[] = {
  "real_T",
  "real32_T",
  "int8_T",
  "uint8_T",
  "int16_T",
  "uint16_T",
  "int32_T",
  "uint32_T",
  "boolean_T",
  "fcn_call_T",
  "int_T",
  "pointer_T",
  "action_T",
  "timer_uint32_pair_T",
  "struct_DSpp81f2dpk9LO8OYuDS2D",
  "struct_mXDYE1zZu7EzH2iXvb11SH",
  "struct_rcDhSIcYe0anGh37xlb6SC",
  "struct_6KsaStIdjpBuRBst70TZDB",
  "robot_model"
};

/* data type transitions for block I/O structure */
static DataTypeTransition rtBTransitions[] = {
  { (char_T *)(&(pDummyInstance->m_BlockIO).robot_model_g), 18, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).Subtract[0]), 0, 0, 161 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).TmpSignalConversionAtSFunctionInport4[0]), 0, 0, 41
  },

  { (char_T *)(&(pDummyInstance->m_BlockIO).enable1), 8, 0, 10 }
  ,

  { (char_T *)(&(pDummyInstance->m_DWork).last_start), 0, 0, 83 },

  { (char_T *)(&(pDummyInstance->m_DWork).JointbasedEALinearization_SubsysRanBC), 2, 0, 3 },

  { (char_T *)(&(pDummyInstance->m_DWork).last_start_not_empty), 8, 0, 16 }
};

/* data type transition table for block I/O structure */
static DataTypeTransitionTable rtBTransTable = {
  7U,
  rtBTransitions
};

/* data type transitions for Parameters structure */
static DataTypeTransition rtPTransitions[] = {
  { (char_T *)(&(pDummyInstance->m_ModelParameters).filter_tau_T_1[0]), 0, 0, 145 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).RigidBodyControllerSelector_Value), 7, 0, 2 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).ManualSwitch2_CurrentSetting), 3, 0, 2 }
};

/* data type transition table for Parameters structure */
static DataTypeTransitionTable rtPTransTable = {
  3U,
  rtPTransitions
};

/* [EOF] controller_dt.h */
