// ****************** controllerCtrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLERCTRL_H_INCLUDED
#define CONTROLLERCTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CcontrollerDrvName "controller"

#include "controllerResource.h"
#include "controllerW32.h"
#include "TcPch.h"
#include "CcontrollerClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CcontrollerCtrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CcontrollerCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CcontrollerCtrl, CcontrollerClassFactory>
{
public:
	CcontrollerCtrl() : ITcOCFCtrlImpl<CcontrollerCtrl, CcontrollerClassFactory>(){}

	virtual ~CcontrollerCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_controllerCtrl)
DECLARE_NOT_AGGREGATABLE(CcontrollerCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CcontrollerCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
