// ****************** controllerServices.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLERSERVICES_H_INCLUDED
#define CONTROLLERSERVICES_H_INCLUDED

#define SRVNAME_controller "controller"

// TcCOM-ClassId of this module: a6356840-c102-48b4-b5d3-6617beaa3b4f
const   CTCID   CID_controller    =  {0xa6356840,0xc102,0x48b4,{0xb5,0xd3,0x66,0x17,0xbe,0xaa,0x3b,0x4f}};

#endif


