// ****************** controllerVersion.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLERVERSION_H_INCLUDED
#define CONTROLLERVERSION_H_INCLUDED

////////////////////////////////////////////////////////////////
//  Version Information
////////////////////////////////////////////////////////////////

#define TWINCAT_TARGET_VERSION  1.2.1235
#define MATLAB_RELEASE	"R2017b"

#endif
