// ****************** controllerInterfaces.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLERINTERFACES_H_INCLUDED
#define CONTROLLERINTERFACES_H_INCLUDED

#include "controllerServices.h"

// define new interfaces provided by this driver

#endif
