// ****************** controller_types.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * controller_types.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "controller".
 *
 * Model version              : 1.2877
 * Simulink Coder version : 8.13 (R2017b) 24-Jul-2017
 * C++ source code generated on : Mon Jun 22 12:41:17 2020
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Execution efficiency
 * Validation result: Not run
 */

#ifndef RTW_HEADER_controller_types_h_
#define RTW_HEADER_controller_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
#include "zero_crossing_types.h"
#ifndef DEFINED_TYPEDEF_FOR_robot_model_
#define DEFINED_TYPEDEF_FOR_robot_model_

typedef struct {
  real_T q[7];
  real_T q_p[7];
  real_T H[16];
  real_T J[42];
  real_T J_p[42];
  real_T M[49];
  real_T C[49];
  real_T g[7];
} robot_model;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_DSpp81f2dpk9LO8OYuDS2D_
#define DEFINED_TYPEDEF_FOR_struct_DSpp81f2dpk9LO8OYuDS2D_

typedef struct {
  boolean_T hanging;
  real_T R_0[9];
  real_T p_0[3];
  real_T n;
  real_T g;
  real_T beta;
  real_T l__0;
  real_T l__1;
  real_T l__2;
  real_T l__3;
  real_T l__4;
  real_T l__5;
  real_T l__6;
  real_T l__7;
  real_T d__1;
  real_T d__3;
  real_T d__5;
  real_T m__l1;
  real_T m__l2;
  real_T m__l3;
  real_T m__l4;
  real_T m__l5;
  real_T m__l6;
  real_T m__l7;
  real_T s__l1x;
  real_T s__l1y;
  real_T s__l1z;
  real_T s__l2x;
  real_T s__l2y;
  real_T s__l2z;
  real_T s__l3x;
  real_T s__l3y;
  real_T s__l3z;
  real_T s__l4x;
  real_T s__l4y;
  real_T s__l4z;
  real_T s__l5x;
  real_T s__l5y;
  real_T s__l5z;
  real_T s__l6x;
  real_T s__l6y;
  real_T s__l6z;
  real_T s__l7x;
  real_T s__l7y;
  real_T s__l7z;
  real_T I__l1xx;
  real_T I__l1yy;
  real_T I__l1zz;
  real_T I__l2xx;
  real_T I__l2yy;
  real_T I__l2zz;
  real_T I__l3xx;
  real_T I__l3yy;
  real_T I__l3zz;
  real_T I__l4xx;
  real_T I__l4yy;
  real_T I__l4zz;
  real_T I__l5xx;
  real_T I__l5yy;
  real_T I__l5zz;
  real_T I__l6xx;
  real_T I__l6yy;
  real_T I__l6zz;
  real_T I__l7xx;
  real_T I__l7yy;
  real_T I__l7zz;
  real_T n__1;
  real_T n__2;
  real_T n__3;
  real_T n__4;
  real_T n__5;
  real_T n__6;
  real_T n__7;
  real_T N[49];
  real_T I__r1xx;
  real_T I__r1yy;
  real_T I__r1zz;
  real_T I__r2xx;
  real_T I__r2yy;
  real_T I__r2zz;
  real_T I__r3xx;
  real_T I__r3yy;
  real_T I__r3zz;
  real_T I__r4xx;
  real_T I__r4yy;
  real_T I__r4zz;
  real_T I__r5xx;
  real_T I__r5yy;
  real_T I__r5zz;
  real_T I__r6xx;
  real_T I__r6yy;
  real_T I__r6zz;
  real_T I__r7xx;
  real_T I__r7yy;
  real_T I__r7zz;
  real_T B[49];
  real_T K__1;
  real_T K__2;
  real_T K__3;
  real_T K__4;
  real_T K__5;
  real_T K__6;
  real_T K__7;
  real_T K[49];
  real_T tau_max[49];
} struct_DSpp81f2dpk9LO8OYuDS2D;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_mXDYE1zZu7EzH2iXvb11SH_
#define DEFINED_TYPEDEF_FOR_struct_mXDYE1zZu7EzH2iXvb11SH_

typedef struct {
  real_T K_tau[7];
  real_T D_tau[7];
} struct_mXDYE1zZu7EzH2iXvb11SH;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_rcDhSIcYe0anGh37xlb6SC_
#define DEFINED_TYPEDEF_FOR_struct_rcDhSIcYe0anGh37xlb6SC_

typedef struct {
  real_T T_a;
  struct_mXDYE1zZu7EzH2iXvb11SH singular_perturbation;
} struct_rcDhSIcYe0anGh37xlb6SC;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_6KsaStIdjpBuRBst70TZDB_
#define DEFINED_TYPEDEF_FOR_struct_6KsaStIdjpBuRBst70TZDB_

typedef struct {
  real_T q_limit_upper[8];
  real_T q_limit_lower[8];
  real_T q_limit_range[8];
  real_T q_limit_slope[8];
  real_T q_limit_gain[8];
  boolean_T barrierfunction;
} struct_6KsaStIdjpBuRBst70TZDB;

#endif

/* Custom Type definition for MATLAB Function: '<S8>/Trajectory generator q' */
#ifndef struct_tag_sIbjh2WiriJotNb04AnYjk
#define struct_tag_sIbjh2WiriJotNb04AnYjk

struct tag_sIbjh2WiriJotNb04AnYjk
{
  real_T K_tau[7];
  real_T D_tau[7];
};

#endif                                 /*struct_tag_sIbjh2WiriJotNb04AnYjk*/

#ifndef typedef_sIbjh2WiriJotNb04AnYjk_controller_T
#define typedef_sIbjh2WiriJotNb04AnYjk_controller_T

typedef struct tag_sIbjh2WiriJotNb04AnYjk sIbjh2WiriJotNb04AnYjk_controller_T;

#endif                                 /*typedef_sIbjh2WiriJotNb04AnYjk_controller_T*/

#ifndef struct_tag_s9rkdF8AeJy2948ssknCHHG
#define struct_tag_s9rkdF8AeJy2948ssknCHHG

struct tag_s9rkdF8AeJy2948ssknCHHG
{
  real_T T_a;
  sIbjh2WiriJotNb04AnYjk_controller_T singular_perturbation;
};

#endif                                 /*struct_tag_s9rkdF8AeJy2948ssknCHHG*/

#ifndef typedef_s9rkdF8AeJy2948ssknCHHG_controller_T
#define typedef_s9rkdF8AeJy2948ssknCHHG_controller_T

typedef struct tag_s9rkdF8AeJy2948ssknCHHG s9rkdF8AeJy2948ssknCHHG_controller_T;

#endif                                 /*typedef_s9rkdF8AeJy2948ssknCHHG_controller_T*/

/* Custom Type definition for MATLAB Function: '<S12>/Gravitation compensation q-based' */
#ifndef struct_tag_sYA73Qec6CU8SREGMfkPEgE
#define struct_tag_sYA73Qec6CU8SREGMfkPEgE

struct tag_sYA73Qec6CU8SREGMfkPEgE
{
  real_T q_limit_upper[8];
  real_T q_limit_lower[8];
  real_T q_limit_range[8];
  real_T q_limit_slope[8];
  real_T q_limit_gain[8];
  boolean_T barrierfunction;
};

#endif                                 /*struct_tag_sYA73Qec6CU8SREGMfkPEgE*/

#ifndef typedef_sYA73Qec6CU8SREGMfkPEgE_controller_T
#define typedef_sYA73Qec6CU8SREGMfkPEgE_controller_T

typedef struct tag_sYA73Qec6CU8SREGMfkPEgE sYA73Qec6CU8SREGMfkPEgE_controller_T;

#endif                                 /*typedef_sYA73Qec6CU8SREGMfkPEgE_controller_T*/

/* Custom Type definition for MATLAB Function: '<Root>/Robot Pose Logger' */
#ifndef struct_tag_sL6LJlPlxhdTxZzXh5NTaQC
#define struct_tag_sL6LJlPlxhdTxZzXh5NTaQC

struct tag_sL6LJlPlxhdTxZzXh5NTaQC
{
  int32_T intNumBits;
};

#endif                                 /*struct_tag_sL6LJlPlxhdTxZzXh5NTaQC*/

#ifndef typedef_sL6LJlPlxhdTxZzXh5NTaQC_controller_T
#define typedef_sL6LJlPlxhdTxZzXh5NTaQC_controller_T

typedef struct tag_sL6LJlPlxhdTxZzXh5NTaQC sL6LJlPlxhdTxZzXh5NTaQC_controller_T;

#endif                                 /*typedef_sL6LJlPlxhdTxZzXh5NTaQC_controller_T*/

/* Custom Type definition for MATLAB Function: '<Root>/Robot Model' */
#ifndef struct_tag_s3SKlq7RIjogRS1TCXHHwEH
#define struct_tag_s3SKlq7RIjogRS1TCXHHwEH

struct tag_s3SKlq7RIjogRS1TCXHHwEH
{
  boolean_T hanging;
  real_T R_0[9];
  real_T p_0[3];
  real_T n;
  real_T g;
  real_T beta;
  real_T l__0;
  real_T l__1;
  real_T l__2;
  real_T l__3;
  real_T l__4;
  real_T l__5;
  real_T l__6;
  real_T l__7;
  real_T d__1;
  real_T d__3;
  real_T d__5;
  real_T m__l1;
  real_T m__l2;
  real_T m__l3;
  real_T m__l4;
  real_T m__l5;
  real_T m__l6;
  real_T m__l7;
  real_T s__l1x;
  real_T s__l1y;
  real_T s__l1z;
  real_T s__l2x;
  real_T s__l2y;
  real_T s__l2z;
  real_T s__l3x;
  real_T s__l3y;
  real_T s__l3z;
  real_T s__l4x;
  real_T s__l4y;
  real_T s__l4z;
  real_T s__l5x;
  real_T s__l5y;
  real_T s__l5z;
  real_T s__l6x;
  real_T s__l6y;
  real_T s__l6z;
  real_T s__l7x;
  real_T s__l7y;
  real_T s__l7z;
  real_T I__l1xx;
  real_T I__l1yy;
  real_T I__l1zz;
  real_T I__l2xx;
  real_T I__l2yy;
  real_T I__l2zz;
  real_T I__l3xx;
  real_T I__l3yy;
  real_T I__l3zz;
  real_T I__l4xx;
  real_T I__l4yy;
  real_T I__l4zz;
  real_T I__l5xx;
  real_T I__l5yy;
  real_T I__l5zz;
  real_T I__l6xx;
  real_T I__l6yy;
  real_T I__l6zz;
  real_T I__l7xx;
  real_T I__l7yy;
  real_T I__l7zz;
  real_T n__1;
  real_T n__2;
  real_T n__3;
  real_T n__4;
  real_T n__5;
  real_T n__6;
  real_T n__7;
  real_T N[49];
  real_T I__r1xx;
  real_T I__r1yy;
  real_T I__r1zz;
  real_T I__r2xx;
  real_T I__r2yy;
  real_T I__r2zz;
  real_T I__r3xx;
  real_T I__r3yy;
  real_T I__r3zz;
  real_T I__r4xx;
  real_T I__r4yy;
  real_T I__r4zz;
  real_T I__r5xx;
  real_T I__r5yy;
  real_T I__r5zz;
  real_T I__r6xx;
  real_T I__r6yy;
  real_T I__r6zz;
  real_T I__r7xx;
  real_T I__r7yy;
  real_T I__r7zz;
  real_T B[49];
  real_T K__1;
  real_T K__2;
  real_T K__3;
  real_T K__4;
  real_T K__5;
  real_T K__6;
  real_T K__7;
  real_T K[49];
  real_T tau_max[49];
};

#endif                                 /*struct_tag_s3SKlq7RIjogRS1TCXHHwEH*/

#ifndef typedef_s3SKlq7RIjogRS1TCXHHwEH_controller_T
#define typedef_s3SKlq7RIjogRS1TCXHHwEH_controller_T

typedef struct tag_s3SKlq7RIjogRS1TCXHHwEH s3SKlq7RIjogRS1TCXHHwEH_controller_T;

#endif                                 /*typedef_s3SKlq7RIjogRS1TCXHHwEH_controller_T*/

/* Parameters (auto storage) */
typedef struct P_controller_T_ P_controller_T;

/* Forward declaration for rtModel */
typedef struct tag_RTM_controller_T RT_MODEL_controller_T;

#endif                                 /* RTW_HEADER_controller_types_h_ */
