// ****************** Ccontroller_ballcatcher_inv_kinClassFactory.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#ifndef CCONTROLLER_BALLCATCHER_INV_KINCLASSFACTORY_H_INCLUDED
#define CCONTROLLER_BALLCATCHER_INV_KINCLASSFACTORY_H_INCLUDED

#include "ObjClassFactory.h"

class Ccontroller_ballcatcher_inv_kinClassFactory : public CObjClassFactory
{
public:
	Ccontroller_ballcatcher_inv_kinClassFactory();
	
	// ITComClassFactory
	DECLARE_CLASS_MAP()
};

#endif
