// ****************** Ccontroller_ballcatcher_inv_kinDrv.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CCONTROLLER_BALLCATCHER_INV_KINDRV_H_INCLUDED
#define CCONTROLLER_BALLCATCHER_INV_KINDRV_H_INCLUDED

#include "TcPch.h"

#define controller_ballcatcher_inv_kinDRV_NAME			"controller_ballcatcher_inv_kin"
#define controller_ballcatcher_inv_kinDRV_Major			1
#define controller_ballcatcher_inv_kinDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			Ccontroller_ballcatcher_inv_kinDrv

#include "ObjDriver.h"

class Ccontroller_ballcatcher_inv_kinDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
  //////////////////////////////////////////////////////
  // VxD-Services exported by this driver
  static unsigned long _cdecl controller_ballcatcher_inv_kin_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( controller_ballcatcher_inv_kinDRV)
	VxD_Service( controller_ballcatcher_inv_kin_GetVersion		)
End_VxD_Service_Table


#endif
