// ****************** Ccontroller_ballcatcher_inv_kinClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "Ccontroller_ballcatcher_inv_kin.h"
#include "Ccontroller_ballcatcher_inv_kinClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(Ccontroller_ballcatcher_inv_kinClassFactory)
	CLASS_ENTRY_RT(CID_controller_ballcatcher_inv_kin,SRVNAME_controller_ballcatcher_inv_kin "!Ccontroller_ballcatcher_inv_kin", Ccontroller_ballcatcher_inv_kin)
END_CLASS_MAP()


Ccontroller_ballcatcher_inv_kinClassFactory::Ccontroller_ballcatcher_inv_kinClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_controller_ballcatcher_inv_kin)); 
}

