// ****************** Ccontroller_ballcatcher_inv_kinDrv.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "Ccontroller_ballcatcher_inv_kinDrv.h"
#include "Ccontroller_ballcatcher_inv_kin.h"
#include "Ccontroller_ballcatcher_inv_kinClassFactory.h"
#include "controller_ballcatcher_inv_kinVersion.h"

DECLARE_GENERIC_DEVICE(controller_ballcatcher_inv_kinDRV)
#undef DEVICE_MAIN

IOSTATUS Ccontroller_ballcatcher_inv_kinDrv::OnLoad( )
{
	TRACE(_T("Ccontroller_ballcatcher_inv_kinClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new Ccontroller_ballcatcher_inv_kinClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID Ccontroller_ballcatcher_inv_kinDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl Ccontroller_ballcatcher_inv_kinDrv::controller_ballcatcher_inv_kin_GetVersion( )
{
	return(0);
}