// ****************** controller_ballcatcher_inv_kin_dt.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * controller_ballcatcher_inv_kin_dt.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "pDummyInstancecontroller_ballcatcher_inv_kin".
 *
 * Model version              : 1.3680
 * Simulink Coder version : 9.0 (R2018b) 24-May-2018
 * C++ source code generated on : Tue Oct 13 22:13:19 2020
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Debugging
 * Validation result: Not run
 */

#include "ext_types.h"

/* data type size table */
static uint_T rtDataTypeSizes[] = {
  sizeof(real_T),
  sizeof(real32_T),
  sizeof(int8_T),
  sizeof(uint8_T),
  sizeof(int16_T),
  sizeof(uint16_T),
  sizeof(int32_T),
  sizeof(uint32_T),
  sizeof(boolean_T),
  sizeof(fcn_call_T),
  sizeof(int_T),
  sizeof(pointer_T),
  sizeof(action_T),
  2*sizeof(uint32_T),
  sizeof(Marker),
  sizeof(struct_EZjJDERKLkL20NuEi0IGyD),
  sizeof(struct_mXDYE1zZu7EzH2iXvb11SH),
  sizeof(struct_Blt0fm03MTggIUFP4njdpF),
  sizeof(struct_45Uo8IsROXGEfVnLRiCZVB),
  sizeof(struct_eTge8mk2lBOxrrglSbzX9G),
  sizeof(robot_model),
  sizeof(struct_PcUEPt9FJnxk90L3HMZRgE),
  sizeof(struct_3PKqMdhV3cqvODbHdLwLIG),
  sizeof(sDzCfTiIapKTB3mCVdDRUZC_controller_ballcatche_T)
};

/* data type name table */
static const char_T * rtDataTypeNames[] = {
  "real_T",
  "real32_T",
  "int8_T",
  "uint8_T",
  "int16_T",
  "uint16_T",
  "int32_T",
  "uint32_T",
  "boolean_T",
  "fcn_call_T",
  "int_T",
  "pointer_T",
  "action_T",
  "timer_uint32_pair_T",
  "Marker",
  "struct_EZjJDERKLkL20NuEi0IGyD",
  "struct_mXDYE1zZu7EzH2iXvb11SH",
  "struct_Blt0fm03MTggIUFP4njdpF",
  "struct_45Uo8IsROXGEfVnLRiCZVB",
  "struct_eTge8mk2lBOxrrglSbzX9G",
  "robot_model",
  "struct_PcUEPt9FJnxk90L3HMZRgE",
  "struct_3PKqMdhV3cqvODbHdLwLIG",
  "sDzCfTiIapKTB3mCVdDRUZC_controller_ballcatche_T"
};

/* data type transitions for block I/O structure */
static DataTypeTransition rtBTransitions[] = {
  { (char_T *)(&(pDummyInstance->m_BlockIO).robot_model_f), 20, 0, 1 },

  { (char_T *)
    (&(pDummyInstance->m_BlockIO).BusConversion_InsertedFor_BallPointSelection_at),
    14, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).t_in), 0, 0, 86 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).x), 0, 0, 19 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).x_out), 0, 0, 3 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).OR), 8, 0, 2 }
  ,

  { (char_T *)(&(pDummyInstance->m_DWork).estimations_last), 23, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_DWork).use_pred_p), 0, 0, 88 },

  { (char_T *)(&(pDummyInstance->m_DWork).Chart2_sfcn_DWORK0), 7, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_DWork).TriggeredSubsystem_SubsysRanBC),
    2, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_DWork).Chart2_sfcn_DWORK1), 3, 0, 2 },

  { (char_T *)(&(pDummyInstance->m_DWork).t_catch_predict_p_not_empty),
    8, 0, 8 }
};

/* data type transition table for block I/O structure */
static DataTypeTransitionTable rtBTransTable = {
  12U,
  rtBTransitions
};

/* data type transitions for Parameters structure */
static DataTypeTransition rtPTransitions[] = {
  { (char_T *)(&(pDummyInstance->m_ModelParameters).optitrack_data), 15, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).param_robot), 19, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).positions), 21, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).estimator_init_struct), 22, 0,
    1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).param_controller), 17, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).timing), 18, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).filter_tau_p_slow_T_1[0]), 0, 0,
    61 },

  { (char_T *)
    (&(pDummyInstance->m_ModelParameters).RigidBodyControllerSelector_Value), 7, 0,
    1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).ManualSwitch2_CurrentSetting),
    3, 0, 2 }
};

/* data type transition table for Parameters structure */
static DataTypeTransitionTable rtPTransTable = {
  9U,
  rtPTransitions
};

/* [EOF] controller_ballcatcher_inv_kin_dt.h */
