// ****************** controller_ballcatcher_inv_kin_types.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * controller_ballcatcher_inv_kin_types.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "controller_ballcatcher_inv_kin".
 *
 * Model version              : 1.3680
 * Simulink Coder version : 9.0 (R2018b) 24-May-2018
 * C++ source code generated on : Tue Oct 13 22:13:19 2020
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Debugging
 * Validation result: Not run
 */

#ifndef RTW_HEADER_controller_ballcatcher_inv_kin_types_h_
#define RTW_HEADER_controller_ballcatcher_inv_kin_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
#include "zero_crossing_types.h"
#ifndef DEFINED_TYPEDEF_FOR_Marker_
#define DEFINED_TYPEDEF_FOR_Marker_

typedef struct {
  int16_T MarkerID;
  int16_T ModelID;
  real_T x;
  real_T y;
  real_T z;
  real_T markerSize;
  real_T bOccluded;
  real_T bPCSolved;
  real_T bModelSolved;
  real_T residualError;
} Marker;

#endif

#ifndef DEFINED_TYPEDEF_FOR_robot_model_
#define DEFINED_TYPEDEF_FOR_robot_model_

typedef struct {
  real_T q[7];
  real_T q_p[7];
  real_T H[16];
  real_T J[42];
  real_T J_p[42];
  real_T M[49];
  real_T C[49];
  real_T g[7];
} robot_model;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_EZjJDERKLkL20NuEi0IGyD_
#define DEFINED_TYPEDEF_FOR_struct_EZjJDERKLkL20NuEi0IGyD_

typedef struct {
  real_T x[246];
  real_T y[246];
  real_T z[246];
} struct_EZjJDERKLkL20NuEi0IGyD;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_mXDYE1zZu7EzH2iXvb11SH_
#define DEFINED_TYPEDEF_FOR_struct_mXDYE1zZu7EzH2iXvb11SH_

typedef struct {
  real_T K_tau[7];
  real_T D_tau[7];
} struct_mXDYE1zZu7EzH2iXvb11SH;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_Blt0fm03MTggIUFP4njdpF_
#define DEFINED_TYPEDEF_FOR_struct_Blt0fm03MTggIUFP4njdpF_

typedef struct {
  real_T g;
  real_T T_a;
  struct_mXDYE1zZu7EzH2iXvb11SH singular_perturbation;
} struct_Blt0fm03MTggIUFP4njdpF;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_45Uo8IsROXGEfVnLRiCZVB_
#define DEFINED_TYPEDEF_FOR_struct_45Uo8IsROXGEfVnLRiCZVB_

typedef struct {
  real_T T_optitrack;
  real_T T_iiwa;
  real_T T_optiTask;
  real_T cycle_time_ratio;
} struct_45Uo8IsROXGEfVnLRiCZVB;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_eTge8mk2lBOxrrglSbzX9G_
#define DEFINED_TYPEDEF_FOR_struct_eTge8mk2lBOxrrglSbzX9G_

typedef struct {
  boolean_T hanging;
  real_T R_0[9];
  real_T p_0[3];
  real_T n;
  real_T g;
  real_T beta;
  real_T l__0;
  real_T l__1;
  real_T l__2;
  real_T l__3;
  real_T l__4;
  real_T l__5;
  real_T l__6;
  real_T l__7;
  real_T d__1;
  real_T d__3;
  real_T d__5;
  real_T m__l1;
  real_T m__l2;
  real_T m__l3;
  real_T m__l4;
  real_T m__l5;
  real_T m__l6;
  real_T m__l7;
  real_T s__l1x;
  real_T s__l1y;
  real_T s__l1z;
  real_T s__l2x;
  real_T s__l2y;
  real_T s__l2z;
  real_T s__l3x;
  real_T s__l3y;
  real_T s__l3z;
  real_T s__l4x;
  real_T s__l4y;
  real_T s__l4z;
  real_T s__l5x;
  real_T s__l5y;
  real_T s__l5z;
  real_T s__l6x;
  real_T s__l6y;
  real_T s__l6z;
  real_T s__l7x;
  real_T s__l7y;
  real_T s__l7z;
  real_T I__l1xx;
  real_T I__l1yy;
  real_T I__l1zz;
  real_T I__l2xx;
  real_T I__l2yy;
  real_T I__l2zz;
  real_T I__l3xx;
  real_T I__l3yy;
  real_T I__l3zz;
  real_T I__l4xx;
  real_T I__l4yy;
  real_T I__l4zz;
  real_T I__l5xx;
  real_T I__l5yy;
  real_T I__l5zz;
  real_T I__l6xx;
  real_T I__l6yy;
  real_T I__l6zz;
  real_T I__l7xx;
  real_T I__l7yy;
  real_T I__l7zz;
  real_T n__1;
  real_T n__2;
  real_T n__3;
  real_T n__4;
  real_T n__5;
  real_T n__6;
  real_T n__7;
  real_T N[49];
  real_T I__r1xx;
  real_T I__r1yy;
  real_T I__r1zz;
  real_T I__r2xx;
  real_T I__r2yy;
  real_T I__r2zz;
  real_T I__r3xx;
  real_T I__r3yy;
  real_T I__r3zz;
  real_T I__r4xx;
  real_T I__r4yy;
  real_T I__r4zz;
  real_T I__r5xx;
  real_T I__r5yy;
  real_T I__r5zz;
  real_T I__r6xx;
  real_T I__r6yy;
  real_T I__r6zz;
  real_T I__r7xx;
  real_T I__r7yy;
  real_T I__r7zz;
  real_T B[49];
  real_T K__1;
  real_T K__2;
  real_T K__3;
  real_T K__4;
  real_T K__5;
  real_T K__6;
  real_T K__7;
  real_T K[49];
  real_T tau_max[49];
  real_T tau_saturation_max[7];
  real_T q_limit_upper[7];
  real_T q_limit_lower[7];
  real_T q_p_limit_upper[7];
  real_T q_p_limit_lower[7];
} struct_eTge8mk2lBOxrrglSbzX9G;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_PcUEPt9FJnxk90L3HMZRgE_
#define DEFINED_TYPEDEF_FOR_struct_PcUEPt9FJnxk90L3HMZRgE_

typedef struct {
  real_T candle[3];
  real_T start[3];
  real_T hand_over[3];
  real_T candle_p[3];
  real_T start_p[3];
  real_T hand_over_p[3];
  real_T T_candle[16];
} struct_PcUEPt9FJnxk90L3HMZRgE;

#endif

#ifndef DEFINED_TYPEDEF_FOR_struct_3PKqMdhV3cqvODbHdLwLIG_
#define DEFINED_TYPEDEF_FOR_struct_3PKqMdhV3cqvODbHdLwLIG_

typedef struct {
  real_T alpha0;
  real_T px_est_last[2];
  real_T Px_last[4];
  real_T py_est_last[2];
  real_T Py_last[4];
  real_T pz_est_last[2];
  real_T Pz_last[4];
  real_T q;
  real_T seed1;
  real_T seed2;
  real_T seed3;
} struct_3PKqMdhV3cqvODbHdLwLIG;

#endif

#if !defined(MATLAB_MEX_FILE)
#undef S_FUNCTION_NAME
#include "Chart2_sfcn_rtw/Chart2_sf.h"
#include "Chart2_sfcn_rtw/Chart2_sf_private.h"
#endif

/* Custom Type definition for MATLAB Function: '<S9>/f_theta_slow' */
#ifndef struct_tag_sIbjh2WiriJotNb04AnYjk
#define struct_tag_sIbjh2WiriJotNb04AnYjk

struct tag_sIbjh2WiriJotNb04AnYjk
{
  real_T K_tau[7];
  real_T D_tau[7];
};

#endif                                 /*struct_tag_sIbjh2WiriJotNb04AnYjk*/

#ifndef typedef_sIbjh2WiriJotNb04AnYjk_controller_ballcatcher_T
#define typedef_sIbjh2WiriJotNb04AnYjk_controller_ballcatcher_T

typedef struct tag_sIbjh2WiriJotNb04AnYjk
  sIbjh2WiriJotNb04AnYjk_controller_ballcatcher_T;

#endif                                 /*typedef_sIbjh2WiriJotNb04AnYjk_controller_ballcatcher_T*/

#ifndef struct_tag_sEsw0EsVUVYKmtCoZBykkPC
#define struct_tag_sEsw0EsVUVYKmtCoZBykkPC

struct tag_sEsw0EsVUVYKmtCoZBykkPC
{
  real_T g;
  real_T T_a;
  sIbjh2WiriJotNb04AnYjk_controller_ballcatcher_T singular_perturbation;
};

#endif                                 /*struct_tag_sEsw0EsVUVYKmtCoZBykkPC*/

#ifndef typedef_sEsw0EsVUVYKmtCoZBykkPC_controller_ballcatche_T
#define typedef_sEsw0EsVUVYKmtCoZBykkPC_controller_ballcatche_T

typedef struct tag_sEsw0EsVUVYKmtCoZBykkPC
  sEsw0EsVUVYKmtCoZBykkPC_controller_ballcatche_T;

#endif                                 /*typedef_sEsw0EsVUVYKmtCoZBykkPC_controller_ballcatche_T*/

/* Custom Type definition for MATLAB Function: '<S11>/Parabola Estimator' */
#ifndef struct_tag_sDzCfTiIapKTB3mCVdDRUZC
#define struct_tag_sDzCfTiIapKTB3mCVdDRUZC

struct tag_sDzCfTiIapKTB3mCVdDRUZC
{
  real_T x0_est;
  real_T vx0_est;
  real_T y0_est;
  real_T vy0_est;
  real_T z0_est;
  real_T vz0_est;
};

#endif                                 /*struct_tag_sDzCfTiIapKTB3mCVdDRUZC*/

#ifndef typedef_sDzCfTiIapKTB3mCVdDRUZC_controller_ballcatche_T
#define typedef_sDzCfTiIapKTB3mCVdDRUZC_controller_ballcatche_T

typedef struct tag_sDzCfTiIapKTB3mCVdDRUZC
  sDzCfTiIapKTB3mCVdDRUZC_controller_ballcatche_T;

#endif                                 /*typedef_sDzCfTiIapKTB3mCVdDRUZC_controller_ballcatche_T*/

/* Custom Type definition for MATLAB Function: '<Root>/Robot Model' */
#ifndef struct_tag_sJOJBOPbTZ83GtnQ5AHgMwC
#define struct_tag_sJOJBOPbTZ83GtnQ5AHgMwC

struct tag_sJOJBOPbTZ83GtnQ5AHgMwC
{
  boolean_T hanging;
  real_T R_0[9];
  real_T p_0[3];
  real_T n;
  real_T g;
  real_T beta;
  real_T l__0;
  real_T l__1;
  real_T l__2;
  real_T l__3;
  real_T l__4;
  real_T l__5;
  real_T l__6;
  real_T l__7;
  real_T d__1;
  real_T d__3;
  real_T d__5;
  real_T m__l1;
  real_T m__l2;
  real_T m__l3;
  real_T m__l4;
  real_T m__l5;
  real_T m__l6;
  real_T m__l7;
  real_T s__l1x;
  real_T s__l1y;
  real_T s__l1z;
  real_T s__l2x;
  real_T s__l2y;
  real_T s__l2z;
  real_T s__l3x;
  real_T s__l3y;
  real_T s__l3z;
  real_T s__l4x;
  real_T s__l4y;
  real_T s__l4z;
  real_T s__l5x;
  real_T s__l5y;
  real_T s__l5z;
  real_T s__l6x;
  real_T s__l6y;
  real_T s__l6z;
  real_T s__l7x;
  real_T s__l7y;
  real_T s__l7z;
  real_T I__l1xx;
  real_T I__l1yy;
  real_T I__l1zz;
  real_T I__l2xx;
  real_T I__l2yy;
  real_T I__l2zz;
  real_T I__l3xx;
  real_T I__l3yy;
  real_T I__l3zz;
  real_T I__l4xx;
  real_T I__l4yy;
  real_T I__l4zz;
  real_T I__l5xx;
  real_T I__l5yy;
  real_T I__l5zz;
  real_T I__l6xx;
  real_T I__l6yy;
  real_T I__l6zz;
  real_T I__l7xx;
  real_T I__l7yy;
  real_T I__l7zz;
  real_T n__1;
  real_T n__2;
  real_T n__3;
  real_T n__4;
  real_T n__5;
  real_T n__6;
  real_T n__7;
  real_T N[49];
  real_T I__r1xx;
  real_T I__r1yy;
  real_T I__r1zz;
  real_T I__r2xx;
  real_T I__r2yy;
  real_T I__r2zz;
  real_T I__r3xx;
  real_T I__r3yy;
  real_T I__r3zz;
  real_T I__r4xx;
  real_T I__r4yy;
  real_T I__r4zz;
  real_T I__r5xx;
  real_T I__r5yy;
  real_T I__r5zz;
  real_T I__r6xx;
  real_T I__r6yy;
  real_T I__r6zz;
  real_T I__r7xx;
  real_T I__r7yy;
  real_T I__r7zz;
  real_T B[49];
  real_T K__1;
  real_T K__2;
  real_T K__3;
  real_T K__4;
  real_T K__5;
  real_T K__6;
  real_T K__7;
  real_T K[49];
  real_T tau_max[49];
  real_T tau_saturation_max[7];
  real_T q_limit_upper[7];
  real_T q_limit_lower[7];
  real_T q_p_limit_upper[7];
  real_T q_p_limit_lower[7];
};

#endif                                 /*struct_tag_sJOJBOPbTZ83GtnQ5AHgMwC*/

#ifndef typedef_sJOJBOPbTZ83GtnQ5AHgMwC_controller_ballcatche_T
#define typedef_sJOJBOPbTZ83GtnQ5AHgMwC_controller_ballcatche_T

typedef struct tag_sJOJBOPbTZ83GtnQ5AHgMwC
  sJOJBOPbTZ83GtnQ5AHgMwC_controller_ballcatche_T;

#endif                                 /*typedef_sJOJBOPbTZ83GtnQ5AHgMwC_controller_ballcatche_T*/

/* Parameters (default storage) */
typedef struct P_controller_ballcatcher_inv_kin_T_
  P_controller_ballcatcher_inv_kin_T;

/* Forward declaration for rtModel */
typedef struct tag_RTM_controller_ballcatcher_inv_kin_T
  RT_MODEL_controller_ballcatcher_inv_kin_T;

#endif                                 /* RTW_HEADER_controller_ballcatcher_inv_kin_types_h_ */
