// ****************** controller_ballcatcher_inv_kinServices.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLER_BALLCATCHER_INV_KINSERVICES_H_INCLUDED
#define CONTROLLER_BALLCATCHER_INV_KINSERVICES_H_INCLUDED

#define SRVNAME_controller_ballcatcher_inv_kin "controller_ballcatcher_inv_kin"

// TcCOM-ClassId of this module: f3c475fc-facb-42bb-8e4e-2776427b4979
const   CTCID   CID_controller_ballcatcher_inv_kin    =  {0xf3c475fc,0xfacb,0x42bb,{0x8e,0x4e,0x27,0x76,0x42,0x7b,0x49,0x79}};

#endif


