// ****************** controller_ballcatcher_inv_kinCtrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLER_BALLCATCHER_INV_KINCTRL_H_INCLUDED
#define CONTROLLER_BALLCATCHER_INV_KINCTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define Ccontroller_ballcatcher_inv_kinDrvName "controller_ballcatcher_inv_kin"

#include "controller_ballcatcher_inv_kinResource.h"
#include "controller_ballcatcher_inv_kinW32.h"
#include "TcPch.h"
#include "Ccontroller_ballcatcher_inv_kinClassFactory.h"
#include "TcOCFCtrlImpl.h"

class Ccontroller_ballcatcher_inv_kinCtrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<Ccontroller_ballcatcher_inv_kinCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<Ccontroller_ballcatcher_inv_kinCtrl, Ccontroller_ballcatcher_inv_kinClassFactory>
{
public:
	Ccontroller_ballcatcher_inv_kinCtrl() : ITcOCFCtrlImpl<Ccontroller_ballcatcher_inv_kinCtrl, Ccontroller_ballcatcher_inv_kinClassFactory>(){}

	virtual ~Ccontroller_ballcatcher_inv_kinCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_controller_ballcatcher_inv_kinCtrl)
DECLARE_NOT_AGGREGATABLE(Ccontroller_ballcatcher_inv_kinCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(Ccontroller_ballcatcher_inv_kinCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
