// ****************** controller_ballcatcher_inv_kinW32.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "TcPch.h"
#include "controller_ballcatcher_inv_kinCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_controller_ballcatcher_inv_kinCtrl		=  {0x8d13d2e2,0xaf15,0x40cb,{0xad,0x89,0x85,0xaf,0xc6,0xdf,0x14,0x3f}};
const   CLSID   LIBID_controller_ballcatcher_inv_kinW32Lib	=  {0x8d13d2e2,0xaf15,0x40cb,{0xad,0x89,0x85,0xaf,0xc6,0xdf,0x14,0x3f}};
const   CLSID   CLSID_controller_ballcatcher_inv_kinCtrl   =  {0x8d13d2e2,0xaf15,0x40cb,{0xad,0x89,0x85,0xaf,0xc6,0xdf,0x14,0x3f}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_controller_ballcatcher_inv_kinCtrl, Ccontroller_ballcatcher_inv_kinCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<Ccontroller_ballcatcher_inv_kinCtrl>* pCcontroller_ballcatcher_inv_kinCtrl = new CComObject<Ccontroller_ballcatcher_inv_kinCtrl>();
	if (pCcontroller_ballcatcher_inv_kinCtrl == NULL) return E_POINTER;
	return pCcontroller_ballcatcher_inv_kinCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}