// ****************** controller_ballcatcher_inv_kin_private.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * controller_ballcatcher_inv_kin_private.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "controller_ballcatcher_inv_kin".
 *
 * Model version              : 1.3680
 * Simulink Coder version : 9.0 (R2018b) 24-May-2018
 * C++ source code generated on : Tue Oct 13 22:13:19 2020
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Debugging
 * Validation result: Not run
 */

#ifndef RTW_HEADER_controller_ballcatcher_inv_kin_private_h_
#define RTW_HEADER_controller_ballcatcher_inv_kin_private_h_
#include "rtwtypes.h"
#include "multiword_types.h"
#include "zero_crossing_types.h"
#if !defined(RTW_GNERATED_SFCN_NOT_PRIVATE_Chart2_sf)
#define RTW_GNERATED_SFCN_NOT_PRIVATE_Chart2_sf
#endif

#if !defined(MATLAB_MEX_FILE)
#undef S_FUNCTION_NAME
#include "Chart2_sfcn_rtw/Chart2_sf.h"
#include "Chart2_sfcn_rtw/Chart2_sf_private.h"
#endif

extern real_T rt_atan2d_snf(real_T u0, real_T u1);
extern "C" void Chart2_sf(SimStruct *rts);

#endif                                 /* RTW_HEADER_controller_ballcatcher_inv_kin_private_h_ */
