// ****************** controller_ballcatcher_inv_kinInterfaces.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLER_BALLCATCHER_INV_KININTERFACES_H_INCLUDED
#define CONTROLLER_BALLCATCHER_INV_KININTERFACES_H_INCLUDED

#include "controller_ballcatcher_inv_kinServices.h"

// define new interfaces provided by this driver

#endif
