// ****************** rt_sfcn_helper.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * rt_sfcn_helper.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "controller_ballcatcher_inv_kin".
 *
 * Model version              : 1.3680
 * Simulink Coder version : 9.0 (R2018b) 24-May-2018
 * C++ source code generated on : Tue Oct 13 22:13:19 2020
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Debugging
 * Validation result: Not run
 */

#ifndef RTW_HEADER_rt_sfcn_helper_h_
#define RTW_HEADER_rt_sfcn_helper_h_
#include "simstruc.h"
#include "rtwtypes.h"
#include "multiword_types.h"
#include "zero_crossing_types.h"
#ifdef __cplusplus

extern "C" {

#endif

  extern int_T rt_CallSys(SimStruct *S, int_T element, int_T tid);
  extern int_T rt_EnableSys(SimStruct *S, int_T element, int_T tid);
  extern int_T rt_DisableSys(SimStruct *S, int_T element, int_T tid);

#ifdef __cplusplus

}                                      /* extern "C" */
#endif
#endif                                 /* RTW_HEADER_rt_sfcn_helper_h_ */
