// ****************** rtGetNaN.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************


    /*
  * rtGetNaN.h
  *
    * Academic License - for use in teaching, academic research, and meeting
* course requirements at degree granting institutions only.  Not for
* government, commercial, or other organizational use. 
  * 
  * Code generation for model "Chart2_sf".
  *
  * Model version              : 1.3679
  * Simulink Coder version : 9.0 (R2018b) 24-May-2018
  * C++ source code generated on : Tue Oct 13 22:10:48 2020
 * 
 * Target selection: rtwsfcn.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Debugging
 * Validation result: Not run
  */


  #ifndef RTW_HEADER_rtGetNaN_h_
  #define RTW_HEADER_rtGetNaN_h_
  

    

  
#include <stddef.h>
  #include "rtwtypes.h"
  #include "rt_nonfinite.h"



  

  

  

  

  

  

  

  

  

  

  

  

  

  

          #ifdef __cplusplus
      extern "C" {
      #endif

    extern real_T rtGetNaN(void);
      extern real32_T rtGetNaNF(void);
          #ifdef __cplusplus
      } /* extern "C" */
      #endif



  

  

  

  

  

    #endif /* RTW_HEADER_rtGetNaN_h_ */
