// ****************** Ccontroller_ballcatcherClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "Ccontroller_ballcatcher.h"
#include "Ccontroller_ballcatcherClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(Ccontroller_ballcatcherClassFactory)
	CLASS_ENTRY_RT(CID_controller_ballcatcher,SRVNAME_controller_ballcatcher "!Ccontroller_ballcatcher", Ccontroller_ballcatcher)
END_CLASS_MAP()


Ccontroller_ballcatcherClassFactory::Ccontroller_ballcatcherClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_controller_ballcatcher)); 
}

