// ****************** Ccontroller_ballcatcherDrv.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "Ccontroller_ballcatcherDrv.h"
#include "Ccontroller_ballcatcher.h"
#include "Ccontroller_ballcatcherClassFactory.h"
#include "controller_ballcatcherVersion.h"

DECLARE_GENERIC_DEVICE(controller_ballcatcherDRV)
#undef DEVICE_MAIN

IOSTATUS Ccontroller_ballcatcherDrv::OnLoad( )
{
	TRACE(_T("Ccontroller_ballcatcherClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new Ccontroller_ballcatcherClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID Ccontroller_ballcatcherDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl Ccontroller_ballcatcherDrv::controller_ballcatcher_GetVersion( )
{
	return(0);
}