// ****************** controller_ballcatcher_dt.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * controller_ballcatcher_dt.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "pDummyInstancecontroller_ballcatcher".
 *
 * Model version              : 1.3592
 * Simulink Coder version : 9.0 (R2018b) 24-May-2018
 * C++ source code generated on : Tue Oct 13 22:18:08 2020
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objective: Debugging
 * Validation result: Not run
 */

#include "ext_types.h"

/* data type size table */
static uint_T rtDataTypeSizes[] = {
  sizeof(real_T),
  sizeof(real32_T),
  sizeof(int8_T),
  sizeof(uint8_T),
  sizeof(int16_T),
  sizeof(uint16_T),
  sizeof(int32_T),
  sizeof(uint32_T),
  sizeof(boolean_T),
  sizeof(fcn_call_T),
  sizeof(int_T),
  sizeof(pointer_T),
  sizeof(action_T),
  2*sizeof(uint32_T),
  sizeof(struct_eTge8mk2lBOxrrglSbzX9G),
  sizeof(struct_mXDYE1zZu7EzH2iXvb11SH),
  sizeof(struct_Blt0fm03MTggIUFP4njdpF),
  sizeof(struct_6KsaStIdjpBuRBst70TZDB),
  sizeof(robot_model),
  sizeof(struct_45Uo8IsROXGEfVnLRiCZVB)
};

/* data type name table */
static const char_T * rtDataTypeNames[] = {
  "real_T",
  "real32_T",
  "int8_T",
  "uint8_T",
  "int16_T",
  "uint16_T",
  "int32_T",
  "uint32_T",
  "boolean_T",
  "fcn_call_T",
  "int_T",
  "pointer_T",
  "action_T",
  "timer_uint32_pair_T",
  "struct_eTge8mk2lBOxrrglSbzX9G",
  "struct_mXDYE1zZu7EzH2iXvb11SH",
  "struct_Blt0fm03MTggIUFP4njdpF",
  "struct_6KsaStIdjpBuRBst70TZDB",
  "robot_model",
  "struct_45Uo8IsROXGEfVnLRiCZVB"
};

/* data type transitions for block I/O structure */
static DataTypeTransition rtBTransitions[] = {
  { (char_T *)(&(pDummyInstance->m_BlockIO).robot_model_f), 18, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).Subtract[0]), 0, 0, 168 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).UnitDelay), 0, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_BlockIO).error), 8, 0, 12 }
  ,

  { (char_T *)(&(pDummyInstance->m_DWork).UnitDelay_DSTATE), 0, 0, 118 },

  { (char_T *)(&(pDummyInstance->m_DWork).UnitDelay1_DSTATE), 8, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_DWork).JointbasedEALinearization_SubsysRanBC),
    2, 0, 3 },

  { (char_T *)(&(pDummyInstance->m_DWork).q0_not_empty), 8, 0, 14 }
};

/* data type transition table for block I/O structure */
static DataTypeTransitionTable rtBTransTable = {
  8U,
  rtBTransitions
};

/* data type transitions for Parameters structure */
static DataTypeTransition rtPTransitions[] = {
  { (char_T *)(&(pDummyInstance->m_ModelParameters).param_robot), 14, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).timing), 19, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).filter_tau_T_1[0]), 0, 0, 126 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).UnitDelay1_InitialCondition), 8, 0, 1 },

  { (char_T *)(&(pDummyInstance->m_ModelParameters).ManualSwitch2_CurrentSetting), 3, 0, 2
  }
};

/* data type transition table for Parameters structure */
static DataTypeTransitionTable rtPTransTable = {
  5U,
  rtPTransitions
};

/* [EOF] controller_ballcatcher_dt.h */
