// ****************** controller_ballcatcherCtrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLER_BALLCATCHERCTRL_H_INCLUDED
#define CONTROLLER_BALLCATCHERCTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define Ccontroller_ballcatcherDrvName "controller_ballcatcher"

#include "controller_ballcatcherResource.h"
#include "controller_ballcatcherW32.h"
#include "TcPch.h"
#include "Ccontroller_ballcatcherClassFactory.h"
#include "TcOCFCtrlImpl.h"

class Ccontroller_ballcatcherCtrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<Ccontroller_ballcatcherCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<Ccontroller_ballcatcherCtrl, Ccontroller_ballcatcherClassFactory>
{
public:
	Ccontroller_ballcatcherCtrl() : ITcOCFCtrlImpl<Ccontroller_ballcatcherCtrl, Ccontroller_ballcatcherClassFactory>(){}

	virtual ~Ccontroller_ballcatcherCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_controller_ballcatcherCtrl)
DECLARE_NOT_AGGREGATABLE(Ccontroller_ballcatcherCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(Ccontroller_ballcatcherCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
