// ****************** controller_ballcatcherServices.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4024
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CONTROLLER_BALLCATCHERSERVICES_H_INCLUDED
#define CONTROLLER_BALLCATCHERSERVICES_H_INCLUDED

#define SRVNAME_controller_ballcatcher "controller_ballcatcher"

// TcCOM-ClassId of this module: fc150844-4666-4420-8fdb-90b5fc684eee
const   CTCID   CID_controller_ballcatcher    =  {0xfc150844,0x4666,0x4420,{0x8f,0xdb,0x90,0xb5,0xfc,0x68,0x4e,0xee}};

#endif


